In [8]:
import sys
import yfinance as yf
from tabulate import tabulate as tb
from financial_performance import *

In [9]:
def target_share_prices(ticker):
    print(ticker)
    income_statement, balance_sheet, statement_of_cash_flows, enterprise_values, price = get_financial_records(ticker)
    #Get Shares Outstanding
    try:
        shares_outstanding = int(float(enterprise_values[0]['Number of Shares']))
    except ValueError:
        print("---Could not get shares outstanding query for " + ticker + " from Financial Modeling Prep. Trying Yahoo Finance...")
        shares_outstanding = yf.Ticker(ticker).info['sharesOutstanding']
    except:
        print("---Could not get number of outstanding shares from Yahoo Finance...")
        shares_outstanding = float('NaN')
        
    def tc_price(income_statement, balance_sheet, statement_of_cash_flows, shares_outstanding):
        try: 
            net_income = float(income_statement[0]['Net Income'])
            net_receivables = float(balance_sheet[0]['Receivables'])-float(balance_sheet[1]['Receivables'])
            net_payables = float(balance_sheet[0]['Payables'])-float(balance_sheet[1]['Payables'])
            income_tax = (float(income_statement[0]['Income Tax Expense']))
            capex = (float(statement_of_cash_flows[0]['Capital Expenditure']))
        except:
            print("---Unable to calculate Ten Cap price.")

        try:
            ten_cap_price = net_income + net_receivables + net_payables + income_tax + capex
            ten_cap_price = round((ten_cap_price*10)/shares_outstanding,2)
        except:
            ten_cap_price = float('NaN')
        return ten_cap_price
                                                                          

    def pbt_price(statement_of_cash_flows, shares_outstanding):
        try:
            pbt_price = round(float(statement_of_cash_flows[0]['Free Cash Flow'])*(1.16*8)/float(enterprise_values[0]['Number of Shares']),2)
        except:
            print("---Unable to calculate Payback Time price.")
            pbt_price = float('NaN')
        return pbt_price

    ten_cap_price = tc_price(income_statement, balance_sheet, statement_of_cash_flows, shares_outstanding)
    payback_time_price = pbt_price(statement_of_cash_flows, shares_outstanding)
    
    return price, ten_cap_price, payback_time_price

In [10]:
target_share_prices("PAYX")

PAYX

(84.7, 44.01, 29.65)

In [ ]:
tickers = open("watchlist.txt", "r")
tickers = tickers.read().splitlines()

In [23]:
stock_prices = []
for ticker in tickers:
    prices = target_share_prices(ticker)
    stock_prices.append({'Company': ticker, 'Price': prices[0], 'Ten Cap Price': prices[1], 'Payback Time Price': prices[2]})
stock_prices = pd.DataFrame(stock_prices)

AAPL
AAPL
ADC
ADC
ALB
ALB
AMAT
AMAT
AMD
AMD
AMZN
AMZN
ATVI
ATVI
AXP
AXP
BA
---Could not get shares outstanding query for BA from Financial Modeling Prep. Trying Yahoo Finance...
---Unable to calculate Payback Time price.
BA
BABA
BABA
BAC
BAC
BLK
BLK
CAG
---Could not get shares outstanding query for CAG from Financial Modeling Prep. Trying Yahoo Finance...
---Unable to calculate Payback Time price.
CAG
BSX
BSX
BYND
Unable to process BYND.
---Could not get number of outstanding shares from Yahoo Finance...
---Unable to calculate Ten Cap price.
---Unable to calculate Payback Time price.
BYND
CCI
CCI
CGC
Unable to process CGC.
---Could not get number of outstanding shares from Yahoo Finance...
---Unable to calculate Ten Cap price.
---Unable to calculate Payback Time price.
CGC
CLF
CLF
CLX
CLX
CONE
CONE
COST
COST
CRM
CRM
CSCO
CSCO
CSX
CSX
CTL
CTL
CTSH
CTSH
CY
CY
DAL
---Could not get shares outstanding query for DAL from Financial Modeling Prep. Trying Yahoo Finance...
---Unable to calculate Payback Time price.
DAL
DFS
---Could not get shares outstanding query for DFS from Financial Modeling Prep. Trying Yahoo Finance...
---Unable to calculate Payback Time price.
DFS
DIS
DIS
DPZ
---Could not get shares outstanding query for DPZ from Financial Modeling Prep. Trying Yahoo Finance...
---Unable to calculate Payback Time price.
DPZ
ETSY
ETSY
FDX
---Could not get shares outstanding query for FDX from Financial Modeling Prep. Trying Yahoo Finance...
---Unable to calculate Payback Time price.
FDX
GOOGL
GOOGL
GOOS
---Could not get shares outstanding query for GOOS from Financial Modeling Prep. Trying Yahoo Finance...
---Unable to calculate Payback Time price.
GOOS
GWPH
GWPH
HD
HD
HSY
---Could not get shares outstanding query for HSY from Financial Modeling Prep. Trying Yahoo Finance...
---Unable to calculate Payback Time price.
HSY
INTC
INTC
JNJ
JNJ
JPM
JPM
KO
KO
KSU
KSU
LRCX
LRCX
LULU
LULU
LUV
LUV
MA
MA
MCD
MCD
MSFT
MSFT
NFLX
NFLX
NKE
NKE
NTDOY
Unable to process NTDOY.
Could not process price for NTDOY.
---Could not get number of outstanding shares from Yahoo Finance...
---Unable to calculate Ten Cap price.
---Unable to calculate Payback Time price.
NTDOY
NVDA
NVDA
O
O
PINS
Unable to process PINS.
---Could not get number of outstanding shares from Yahoo Finance...
---Unable to calculate Ten Cap price.
---Unable to calculate Payback Time price.
PINS
PG
---Could not get shares outstanding query for PG from Financial Modeling Prep. Trying Yahoo Finance...
---Unable to calculate Payback Time price.
PG
PSTG
PSTG
PYPL
PYPL
RH
RH
ROKU
ROKU
SHAK
---Could not get shares outstanding query for SHAK from Financial Modeling Prep. Trying Yahoo Finance...
---Unable to calculate Payback Time price.
SHAK
SMG
---Could not get shares outstanding query for SMG from Financial Modeling Prep. Trying Yahoo Finance...
---Unable to calculate Payback Time price.
SMG
SNOW
Unable to process SNOW.
Could not process price for SNOW.
---Could not get number of outstanding shares from Yahoo Finance...
---Unable to calculate Ten Cap price.
---Unable to calculate Payback Time price.
SNOW
SPOT
Unable to process SPOT.
---Could not get number of outstanding shares from Yahoo Finance...
---Unable to calculate Ten Cap price.
---Unable to calculate Payback Time price.
SPOT
SQ
SQ
STOR
STOR
STZ
STZ
T
---Could not get shares outstanding query for T from Financial Modeling Prep. Trying Yahoo Finance...
---Unable to calculate Payback Time price.
T
TGT
TGT
TSLA
TSLA
TTWO
TTWO
TWLO
TWLO
TWTR
TWTR
ULTA
ULTA
UNH
UNH
UTX
UTX
V
V
VZ
VZ
XPO
XPO
YETI
Unable to process YETI.
---Could not get number of outstanding shares from Yahoo Finance...
---Unable to calculate Ten Cap price.
---Unable to calculate Payback Time price.
YETI

In [24]:
stock_prices

   Company    Price  Ten Cap Price  Payback Time Price
0     AAPL  222.730         169.11              119.01
1      ADC   72.870        -172.21             -154.48
2      ALB   67.370          29.96              -13.04
3     AMAT   52.060          42.18               28.63
4      AMD   30.435          11.19               -1.13
..     ...      ...            ...                 ...
75     UTX  137.650         113.20               50.63
76       V  175.280          48.36               43.09
77      VZ   59.920          12.90               39.71
78     XPO   73.630          -9.56               37.88
79    YETI   28.820            NaN                 NaN

[80 rows x 4 columns]

In [ ]:
print(stock_prices.to_string())